class demo_locators:
    login=('class name','ico-login')
    username_text=('id','Email')
    password_text=('name','Password')
    submit_btn=('xpath','//input[@value="Log in"]')
    country_drp=('id','country')
    colours=('id','colors')
    name_locator=('id','name')
    email_locator=('id','email')
    phn_locator=('id','phone')
    address_locator=('id','textarea')
    gender_locator=('id','female')
    sunday_locator=('id','sunday')
    tuesday_locator=('id','tuesday')
    friday_locator=('id','friday')
    datepicker_locator=('id','datepicker')
    month_locator=('xpath','//span[@class="ui-datepicker-month"]')
    year_locator=('xpath','//span[@class="ui-datepicker-year"]')
    next_locator=('xpath',"//span[text()='Next']")
    prev_locator=('xpath',"//span[text()='Prev']")
    Dates_locator=('xpath','//table[@class="ui-datepicker-calendar"]/tbody/tr/td/a')
    orange_hrm=('link text','orange HRM')
    posts_locator=('xpath',"//a[text()='Posts (Atom)']")
    loc_rows=('xpath','//table[@name="BookTable"]/tbody/tr')
    loc_cols=('xpath','//table[@name="BookTable"]/tbody/tr/th')
    subject_locator=('xpath','//table[@name="BookTable"]/tbody/tr/td[3]')
    device_Names=('xpath','//table[@id="productTable"]/tbody/tr/td[2]')
    accept_locator=('xpath',"//button[text()='Alert']")
    confirm_locator=('xpath',"//button[text()='Confirm Box']")
    prompt_locator=('xpath',"//button[text()='Prompt']")
    doubleclick_locator=('xpath',"//button[text()='Copy Text']")
    first_frame=('xpath','//iframe[@class="w-full h-96"]')
    second_frame=('xpath','//section[@class="main_form_container"]/div[2]/iframe')
    frame_email=('id','email')
    frame_pwd=('id','password')
    frame_cpwd=('id','confirm-password')

