from Lib.lib2 import Base
from time import sleep


class practise(Base):
    name_locator = ('id', 'name')
    email_locator = ('id', 'email')
    phn_locator = ('id', 'phone')
    address_locator = ('id', 'textarea')
    gender_locator = ('id', 'female')
    sunday_locator = ('id', 'sunday')
    thursday_locator = ('id', 'thursday')
    days_selection = ('xpath', '//div[@class="form-check form-check-inline"]/label')
    country_locator = ('id', 'country')
    colors_locator = ('id', 'colors')
    datepicker1_locator = ('xpath', '//input[@id="datepicker"]')
    month_locator = ('xpath', '//span[@class="ui-datepicker-month"]')
    year_locator = ('xpath', '//span[@class="ui-datepicker-year"]')
    next_locator = ('xpath', '//a[@title="Next"]')
    datepicker2_locator = ('id', 'txtDate')
    link_locator = ('xpath', "//a[text()='Posts (Atom)']")
    row_locator = ('xpath', '//table[@id="taskTable"]/tbody/tr')
    col_locator = ('xpath', '//table[@id="taskTable"]/thead/tr/th')
    wiki_locator = ("id", "Wikipedia1_wikipedia-search-input")
    wiki_search_btn=('xpath','//input[@class="wikipedia-search-button"]')
    mahesh_babu_locator=('xpath',"//a[text()='Mahesh Babu']")
    start_btn=('xpath',"//button[text()='START']")
    new_tab_locator=('xpath',"//button[text()='New Tab']")
    sample_alert=('xpath',"//button[text()='Simple Alert']")

    def prac(self, name, email, phn, date_value, wiki_data):
        self.send_data(self.name_locator, name)
        sleep(2)
        self.send_data(self.email_locator, email)
        sleep(2)
        self.send_data(self.phn_locator, phn)
        sleep(2)
        self.key_boardactions(self.phn_locator)
        sleep(2)
        self.click(self.gender_locator)
        sleep(2)
        self.Days_selection(self.days_selection)
        sleep(2)
        self.drop(self.country_locator)
        sleep(2)
        self.drop_colours(self.colors_locator)
        sleep(2)
        self.click1(self.datepicker1_locator)
        sleep(2)
        self.calender(self.next_locator)
        sleep(2)
        self.send_data(self.datepicker2_locator, date_value)
        sleep(2)
        # self.click_common(self.link_locator)
        # sleep(4)
        # self.windows()
        sleep(5)
        self.webtable()
        sleep(2)
        self.dynamic_web(self.row_locator, self.col_locator)
        sleep(2)
        self.check_boxes_table()
        sleep(2)
        self.send_data(self.wiki_locator, wiki_data)
        sleep(2)
        self.click_common(self.wiki_search_btn)
        sleep(2)
        self.click_common(self.mahesh_babu_locator)
        sleep(2)
        self.windows()
        sleep(5)
        self.click_common(self.start_btn)
        sleep(2)
